export const BondActions = {
  FETCH_BOND_INFO: "bond/FETCH_BOND_INFO",
  DID_FETCH_BOND_INFO: "bond/DID_FETCH_BOND_INFO",
  DID_FETCH_BOND_INFO_FAIL: "bond/DID_FETCH_BOND_INFO_FAIL",

  SET_CHART_PERIOD: "bond/SET_CHART_PERIOD",
  SET_Y_AXIS: "bond/SET_Y_AXIS",
};
